import type { Metadata, Viewport } from 'next';
import './globals.css';
import MainNavigation from '@/components/MainNavigation';
import App from '@/app/_app';

export const metadata: Metadata = {
  title: 'DSB - in beautiful',
  description: 'Generated by create next app',
  other: {
    'apple-mobile-web-app-capable': 'yes',
  },
};
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>
        <App>
          {children}
          <MainNavigation />
        </App>
      </body>
    </html>
  );
}
